name: "Set up a learning space based on a yaml template"
description: "Run the single-user action to set up your learning space based on the micromaterials that are present in your template"
author: "lpmi-13"
inputs:
  path:
    description: "The path to the yaml configuration template. This can be a file or a URL available on a network (eg. https://github.com/lpmi-13/learning-space-templates/.learning/example.yml)"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'book-open'
  color: 'green'
