name: Test
on: [push, pull_request]
jobs:
  test:
    name: Run some Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - uses: actions/checkout@v1

      - name: Test
        # this currently does nothing, but we can add some tests later
        run: |
          python -m unittest
